---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Gather EC2 remote facts.
      ec2_remote_facts:
        region: "us-east-1"
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
        filters:
          instance-state-name: running
      register: facts
    - debug: 
        var: facts
