---
- name: Terminate an EC2 instance
  hosts: localhost
  gather_facts: True
  tasks:
    - name: Terminate instance
      ec2:
         instance_ids: i-0ac873e3ee3cfa54d
         wait: true
         state: absent
         region: us-east-1
         aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
         aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
      register: ec2
    - name: Print all ec2 variables
      debug: var=ec2




- name: add host to group 'just_created' with variable foo=42
      add_host:
    

- name: Install stuff into ec2 hosts
  hosts: ec2_hosts
  become: yes
  roles:
    - 
